/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "DBHandle.h"

bool_t
xdr_record (XDR *xdrs, record *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->rollno))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->marks))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user_record (XDR *xdrs, user_record *objp)
{
	register int32_t *buf;

	 if (!xdr_record (xdrs, objp))
		 return FALSE;
	return TRUE;
}
