/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "porth.h"

bool_t
xdr_inputstruct (XDR *xdrs, inputstruct *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->host1, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->start))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->end))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_outputstruct (XDR *xdrs, outputstruct *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  PORTSLIMIT )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->tot))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->port_no, PORTSLIMIT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->tot);
			{
				register int *genp;

				for (i = 0, genp = objp->port_no;
					i < PORTSLIMIT; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  PORTSLIMIT )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->tot))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->port_no, PORTSLIMIT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->tot = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->port_no;
					i < PORTSLIMIT; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->tot))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->port_no, PORTSLIMIT,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_in (XDR *xdrs, in *objp)
{
	register int32_t *buf;

	 if (!xdr_inputstruct (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_out (XDR *xdrs, out *objp)
{
	register int32_t *buf;

	 if (!xdr_outputstruct (xdrs, objp))
		 return FALSE;
	return TRUE;
}
