/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PORTH_H_RPCGEN
#define _PORTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define PORTSLIMIT 50

struct inputstruct {
	char host1[40];
	int start;
	int end;
};
typedef struct inputstruct inputstruct;

struct outputstruct {
	int tot;
	int port_no[PORTSLIMIT];
};
typedef struct outputstruct outputstruct;

typedef inputstruct in;

typedef outputstruct out;

#define PORTPROG 22855
#define PORTS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getopenports 1
extern  out * getopenports_1(in *, CLIENT *);
extern  out * getopenports_1_svc(in *, struct svc_req *);
extern int portprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getopenports 1
extern  out * getopenports_1();
extern  out * getopenports_1_svc();
extern int portprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputstruct (XDR *, inputstruct*);
extern  bool_t xdr_outputstruct (XDR *, outputstruct*);
extern  bool_t xdr_in (XDR *, in*);
extern  bool_t xdr_out (XDR *, out*);

#else /* K&R C */
extern bool_t xdr_inputstruct ();
extern bool_t xdr_outputstruct ();
extern bool_t xdr_in ();
extern bool_t xdr_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PORTH_H_RPCGEN */
