/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AVG1_H_RPCGEN
#define _AVG1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SQRPROG 22855
#define SQRVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define square 23
extern  double * square_1(double *, CLIENT *);
extern  double * square_1_svc(double *, struct svc_req *);
extern int sqrprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define square 23
extern  double * square_1();
extern  double * square_1_svc();
extern int sqrprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AVG1_H_RPCGEN */
